# Generated by Django 5.1.7 on 2025-03-15 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DITTEApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('home_district', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('sub_county', models.CharField(max_length=50)),
                ('district_of_residence', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('religious_affiliation', models.CharField(blank=True, max_length=50, null=True)),
                ('programme', models.CharField(choices=[('Agricultural Production', 'Agricultural Production'), ('Automobile Engineering', 'Automobile Engineering'), ('Civil and Building Engineering', 'Civil and Building Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Leather Tanning & Leather Goods Production', 'Leather Tanning & Leather Goods Production'), ('Metal Fabrication', 'Metal Fabrication'), ('Tailoring and Garments Design', 'Tailoring and Garments Design')], max_length=100)),
                ('programme_status', models.CharField(choices=[('Full Time Government (1 Year)', 'Full Time Government (1 Year)'), ('Full Time Private (1 Year)', 'Full Time Private (1 Year)')], max_length=50)),
                ('sponsor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sponsor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sponsor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('declaration_signature', models.CharField(max_length=100)),
            ],
        ),
    ]
