# Generated by Django 5.1.7 on 2025-03-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
                ('children', models.IntegerField(default=0)),
                ('religion', models.CharField(max_length=100)),
                ('next_of_kin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_record', models.TextField(help_text='Institution, Role, From, To')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EducationBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_background', models.TextField(help_text='School Name, Period, Qualification, Grade')),
                ('major_subjects', models.TextField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationEndorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_signature', models.FileField(upload_to='signatures/')),
                ('endorser_name', models.CharField(max_length=200)),
                ('endorser_designation', models.CharField(max_length=200)),
                ('endorser_institution', models.CharField(max_length=200)),
                ('endorser_address', models.TextField()),
                ('endorser_signature', models.FileField(upload_to='signatures/')),
                ('official_stamp', models.FileField(upload_to='stamps/')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=200)),
                ('programme_status', models.CharField(max_length=100)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=200)),
                ('sponsor_address', models.TextField()),
                ('sponsor_phone', models.CharField(max_length=15)),
                ('sponsor_email', models.EmailField(max_length=254)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.personalinfo')),
            ],
        ),
    ]
