# Generated by Django 5.1.7 on 2025-04-07 19:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_educationdocument_application_education_pdfs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_documents', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='educationdocument',
            name='pdf_file',
            field=models.FileField(upload_to='education_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
