# Generated by Django 5.1.7 on 2025-04-07 20:33

import applications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_educationdocument_application_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=applications.models.education_image_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_images', to='applications.application')),
            ],
        ),
    ]
