# Generated by Django 5.1.7 on 2025-03-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Admitted', 'Admitted'), ('Declined', 'Declined')], default='Submitted', max_length=10),
        ),
    ]
