# Generated by Django 5.1.7 on 2025-04-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_educationimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_document', models.FileField(upload_to='testimonials/')),
            ],
        ),
    ]
