# Generated by Django 5.1.7 on 2025-04-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_studenttestimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.FileField(upload_to='academic_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
