# Generated by Django 5.1.7 on 2025-04-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_academicdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='programme',
            field=models.CharField(choices=[('Agricultural Production', 'Agricultural Production'), ('Automobile Engineering', 'Automobile Engineering'), ('Civil and Building Engineering', 'Civil and Building Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Leather Tanning & Leather Goods Production', 'Leather Tanning & Leather Goods Production'), ('Metal Fabrication', 'Metal Fabrication'), ('Tailoring and Garments Design', 'Tailoring and Garments Design'), ('Electronics Engineering', 'Electronics Engineering')], max_length=255),
        ),
    ]
